# Generated by Django 5.2.5 on 2025-08-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('farmer', 'Farmer'), ('vet', 'Vet Doctor'), ('staff', 'Staff')], default='farmer', max_length=20),
        ),
    ]
