# Generated by Django 5.2.5 on 2025-09-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
