# Generated by Django 5.2.5 on 2025-09-17 11:37

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_treatment_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='mpesa_callback_body',
            field=models.JSONField(blank=True, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='mpesa_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='mpesa_result_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='mpesa_transaction_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
